//! Native MLOW specification generation, snapshot assembly and pinned verification.
mod assemble;
use anyhow::{Context, Result, ensure};
use clap::Subcommand;
use serde_json::{Value, json};
use std::path::{Path, PathBuf};
use xtask_support::{output_tree, read_json, sha256, write_json};

const J: &str = "JgwtTQVeWPm";
const S: &str = "S_ivh1PriOA";
const J_RUNS: &[&str] = &[
    "mlow_110frames",
    "mlow_120ms",
    "mlow_dtx_off",
    "mlow_fe_trace",
    "mlow_signal_trace",
    "mlow_kernel_trace",
    "mlow_postfilter_trace",
    "mlow_params_trace",
    "mlow_gennoise_trace",
];
const S_RUNS: &[&str] = &["mlow_110frames_s", "mlow_120ms_s"];
#[derive(Subcommand)]
pub enum Task {
    /// Re-derive all locked outputs (or validate an existing run), then assemble fixtures.
    Verify {
        #[arg(long, default_value="all", value_parser=["all", J, S])]
        capture: String,
        #[arg(long)]
        out: Option<PathBuf>,
        /// Validate all cached hashes before assembly instead of running the guest again.
        #[arg(long)]
        from_derived: bool,
        #[arg(long, conflicts_with = "refresh_spec_hashes")]
        update_lock: bool,
        /// Refresh serialization hashes only; every module and output tree must remain identical.
        #[arg(long)]
        refresh_spec_hashes: bool,
    },
    /// Generate every derived specification, optionally refusing source drift.
    Specs {
        #[arg(long)]
        out: Option<PathBuf>,
        #[arg(long)]
        check: bool,
    },
    /// Generate one trace spec; KIND is fe, signal, kernel, postfilter, params or gennoise.
    Spec {
        kind: String,
        #[arg(long)]
        out: PathBuf,
        #[arg(long, default_value_t = 330)]
        lsf_count: usize,
        #[arg(long, default_value_t = 1099)]
        end: usize,
    },
    /// Assemble all fixtures from verified snapshot output directories.
    Assemble {
        kind: Option<String>,
        #[arg(long)]
        out: PathBuf,
        #[arg(long)]
        run: Option<PathBuf>,
        #[arg(long, alias = "lsf-output", alias = "harm-output")]
        secondary: Option<PathBuf>,
        #[arg(long, default_value_t = 330)]
        lsf_count: usize,
    },
}

fn trace(root: &Path, kind: &str, count: usize, end: usize) -> Result<Value> {
    let catalog: Value = serde_json::from_str(include_str!("mlow-recipes.json"))?;
    let recipe = catalog.get(kind).context("unknown MLOW trace kind")?;
    let mut base = read_json(&root.join("specs/mlow_110frames.json"))?;
    base["comment"] = recipe["comment"].clone();
    base["functions"]
        .as_object_mut()
        .context("functions")?
        .extend(
            recipe["functions"]
                .as_object()
                .context("recipe functions")?
                .clone(),
        );
    let mut captures = recipe["captures"].as_array().context("captures")?.clone();
    for step in &mut captures {
        if step["func"] == "lsf_core" {
            step["count"] = json!(count);
            if step["instruction"] != 0 {
                step["instruction"] = json!(end);
            }
        }
    }
    captures.extend(base["steps"].as_array().context("steps")?.iter().cloned());
    base["steps"] = json!(captures);
    Ok(base)
}
fn generated_specs(root: &Path) -> Result<Vec<(String, Value)>> {
    let mut generated = Vec::new();
    let s_base = read_json(&root.join("specs/mlow_encode_s.json"))?;
    for name in ["mlow_110frames", "mlow_120ms"] {
        let mut spec = read_json(&root.join(format!("specs/{name}.json")))?;
        spec["module"] = s_base["module"].clone();
        spec["functions"] = s_base["functions"].clone();
        spec["comment"] = json!([
            "Generated by cargo xt mlow specs; S layout re-derived from alloc/open/init.",
            "All J output hashes retained: this run must prove complete J/S equivalence."
        ]);
        for step in spec["steps"].as_array_mut().context("steps")? {
            if (step["op"] == "malloc" && step["as"] == "attr")
                || (step["op"] == "fill" && step["ptr"] == "$attr")
            {
                step["len"] = json!(1216);
            }
            if step["op"] == "write"
                && step["ptr"] == "$state"
                && let Some(at @ 8..=100) = step["at"].as_u64()
            {
                step["hex"] = json!(hex::encode((5282u32 - at as u32 / 4).to_le_bytes()));
            }
            if step["op"] == "write" && step["ptr"] == "$codec" {
                let value = match step["at"].as_u64() {
                    Some(12) => Some(1398252u32),
                    Some(20) => Some(1325408u32),
                    _ => None,
                };
                if let Some(value) = value {
                    step["hex"] = json!(hex::encode(value.to_le_bytes()));
                }
            }
            if step["op"] == "read_u32" && step["ptr"] == 1719408 {
                step["ptr"] = json!(1740400);
            }
        }
        generated.push((format!("{name}_s.json"), spec));
    }
    for kind in ["fe", "signal", "kernel", "postfilter", "params", "gennoise"] {
        generated.push((
            format!("mlow_{kind}_trace.json"),
            trace(root, kind, 330, 1099)?,
        ));
    }
    Ok(generated)
}
fn specs(root: &Path, out: &Path, check: bool) -> Result<()> {
    for (name, value) in generated_specs(root)? {
        if check {
            ensure!(
                read_json(&root.join("specs").join(&name))? == value,
                "generated spec drift: {name}"
            );
        } else {
            write_json(&out.join(name), &value)?;
        }
    }
    Ok(())
}
fn verify(
    root: &Path,
    out: &Path,
    capture: &str,
    cached: bool,
    update: bool,
    refresh: bool,
) -> Result<()> {
    ensure!(
        !(update || refresh) || capture == "all",
        "lock refresh requires both captures"
    );
    ensure!(
        !cached || !(update || refresh),
        "cached outputs cannot refresh a lock"
    );
    specs(root, &root.join("specs"), true)?;
    let expected = read_json(&root.join("specs/mlow.lock.json"))?;
    let inputs = json!({"synth_mic.raw":sha256(&std::fs::read(root.join("specs/synth_mic.raw"))?),"synth120_head.raw":sha256(&std::fs::read(root.join("specs/synth120_head.raw"))?)});
    if !update {
        ensure!(inputs == expected["inputs"], "synthetic input drift");
    }
    let mut actual = json!({"schema":1,"inputs":inputs,"runs":{}});
    let captures = if capture == "all" {
        vec![J, S]
    } else {
        vec![capture]
    };
    if !cached {
        super::fetch(root, &root.join("wasm"), Some(&captures))?;
    }
    // Specs retain repository-relative input paths; no shell or subprocess needs to interpret them.
    let previous_dir = std::env::current_dir()?;
    std::env::set_current_dir(root)?;
    let result = (|| -> Result<()> {
        for id in captures {
            for name in if id == J { J_RUNS } else { S_RUNS } {
                let run = out.join(name);
                if !update && !refresh {
                    let source = std::fs::read(root.join(format!("specs/{name}.json")))?;
                    ensure!(
                        expected["runs"][name]["spec_sha256"].as_str()
                            == Some(sha256(&source).as_str()),
                        "current spec differs from lock: {name}"
                    );
                }
                if !cached {
                    oracle_core::derive::run_spec(
                        &root.join(format!("specs/{name}.json")),
                        &root.join(format!("wasm/{id}.wasm")),
                        &run,
                    )?;
                }
                let manifest = read_json(&run.join("manifest.json"))?;
                let record = json!({"module":manifest["module"],"spec_sha256":manifest["spec_sha256"],"resolutions":manifest["resolutions"],"outputs":manifest["outputs"].as_array().context("outputs")?.len(),"tree_sha256":output_tree(&manifest,&run)?});
                if refresh {
                    for key in ["module", "resolutions", "outputs", "tree_sha256"] {
                        ensure!(
                            record[key] == expected["runs"][name][key],
                            "oracle output drift during serialization migration: {name}/{key}"
                        );
                    }
                } else if !update {
                    ensure!(record == expected["runs"][name], "derivation drift: {name}");
                }
                actual["runs"][name] = record;
                println!("{id}: {name}: verified");
            }
        }
        if capture == "all" || capture == J {
            assemble::all(out)?;
        }
        if update || refresh {
            write_json(&root.join("specs/mlow.lock.json"), &actual)?;
        }
        Ok(())
    })();
    std::env::set_current_dir(previous_dir)?;
    result
}
pub fn run(root: &Path, task: Task) -> Result<()> {
    match task {
        Task::Specs { out, check } => specs(root, &out.unwrap_or(root.join("specs")), check),
        Task::Spec {
            kind,
            out,
            lsf_count,
            end,
        } => write_json(&out, &trace(root, &kind, lsf_count, end)?),
        Task::Assemble {
            kind,
            out,
            run,
            secondary,
            lsf_count,
        } => {
            if let Some(kind) = kind {
                assemble::one(
                    &kind,
                    &run.context("--run is required for a single trace")?,
                    &out,
                    secondary.as_deref(),
                    lsf_count,
                )
            } else {
                assemble::all(&std::path::absolute(out)?)
            }
        }
        Task::Verify {
            capture,
            out,
            from_derived,
            update_lock,
            refresh_spec_hashes,
        } => verify(
            root,
            &std::path::absolute(out.unwrap_or(root.join(".derive-mlow")))?,
            &capture,
            from_derived,
            update_lock,
            refresh_spec_hashes,
        ),
    }
}
