#!/usr/bin/env python3
"""Generate S stream specs from the pinned J programs after re-deriving layouts.

S#6947 assigns slots 5280..5257 at state+8..100. S#6950 reads attr+1200
(skip decoder creation), where J#6658 reads +1176. S#11036 sets +1740400.
Only capture-specific layout is carried here; output hashes remain J's so the
S runs must prove identical packet and PCM bytes over the complete stream.
"""
import copy
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

def save(path, value):
    path.write_text(json.dumps(value, indent=2) + '\n')

def main(destination=ROOT / "specs"):
    s_base = json.loads((ROOT / 'specs/mlow_encode_s.json').read_text())
    for stem in ['mlow_110frames', 'mlow_120ms']:
        spec = json.loads((ROOT / f'specs/{stem}.json').read_text())
        spec['module'] = copy.deepcopy(s_base['module'])
        spec['functions'] = copy.deepcopy(s_base['functions'])
        spec['comment'] = ['Generated by scripts/mlow/capture_specs.py; S layout re-derived from alloc/open/init.',
                           'All J output hashes retained: this run must prove complete J/S equivalence.']
        for step in spec['steps']:
            if (step['op'] == 'malloc' and step.get('as') == 'attr'
                or step['op'] == 'fill' and step.get('ptr') == '$attr'):
                step['len'] = 1216
            if step['op'] == 'write' and step.get('ptr') == '$state' and 8 <= step.get('at', 0) <= 100:
                step['hex'] = (5282 - step['at'] // 4).to_bytes(4, 'little').hex()
            if step['op'] == 'write' and step.get('ptr') == '$codec':
                values = {12: 1398252, 20: 1325408}
                if step['at'] in values:
                    step['hex'] = values[step['at']].to_bytes(4, 'little').hex()
            if step['op'] == 'read_u32' and step.get('ptr') == 1719408:
                step['ptr'] = 1740400
        save(destination / f'{stem}_s.json', spec)

if __name__ == '__main__':
    main()
