//! Emitting Rust that compiles.
//!
//! The rule this backend is built around is that the output always builds. Not
//! "usually", and not "after you fix the three places it gave up" — a
//! decompiler whose output does not compile cannot be checked against the
//! module it came from, and an unchecked decompilation is a story about the
//! code rather than a reading of it.
//!
//! Three consequences run through everything below:
//!
//! - **Nothing is skipped.** An opcode with no lowering is an error from
//!   [`crate::module`], not a comment in the output.
//! - **Values that outlive an effect are named.** wasm's operand stack has no
//!   Rust equivalent, so a pushed value is either folded into its consumer (only
//!   when it is a constant, a local or a global read) or spilled to a `let`
//!   before anything can change what it would have read.
//! - **Structure is taken, not recovered.** wasm's `block`/`loop`/`if` nest, and
//!   Rust's labelled blocks and loops nest the same way. Every frame becomes
//!   `'bN: { .. }` or `'bN: loop { .. }`, and a `br` becomes `break 'bN` or
//!   `continue 'bN`. There is no control-flow graph in this file, because there
//!   is no control-flow graph in the input.
//!
//! What this level does *not* do is recover types, structs or the shadow stack:
//! linear memory stays a byte vector, and a C local that lived in it stays an
//! address. That is the next level's job, and it is only safe to attempt on top
//! of something already known to run.

use std::collections::BTreeSet;
use std::fmt::Write as _;

// `Frame` is taken in this file by the control-flow frame, which is a
// different thing entirely: one is a `block` being emitted, the other is the C
// stack frame the module carved out of linear memory.
use crate::analysis::{self, Analysis, Evidence, Frame as StackFrame};
use crate::error::{Error, Result};
use crate::module::{
    BlockType, ConstExpr, ExportKind, Func, LoadKind, Module, Op, StoreKind, ValType,
};
use crate::ops::{self, NumOp};

/// The header every part file carries: the same lint allowances as `mod.rs`,
/// which are per-file and do not reach across module boundaries.
const PART_HEADER: &str = concat!(
    "// Generated by unwasm. Do not edit: regenerate from the module.\n",
    "//\n",
    "// One of several part files. rustc partitions codegen units along module\n",
    "// boundaries, so splitting the functions across modules is what keeps a\n",
    "// large module compiling in a reasonable time.\n",
    "\n",
    "#![allow(\n",
    "    dead_code,\n",
    "    unused_mut,\n",
    "    unused_variables,\n",
    "    unused_assignments,\n",
    "    unused_labels,\n",
    "    unused_parens,\n",
    "    unreachable_code,\n",
    "    non_snake_case,\n",
    "    clippy::all,\n",
    "    clippy::pedantic\n",
    ")]\n\n",
);

/// The runtime, as text, for embedding in the output.
///
/// The tests are cut off: they belong to this crate, and carrying four hundred
/// lines of them into every generated module would bury the code being read.
#[must_use]
pub fn runtime_source() -> &'static str {
    strip_tests(include_str!("rt.rs"))
}

/// Cuts a source file at its test module.
///
/// Separate from [`runtime_source`] so the "there was nothing to cut" case can
/// be tested: `rt.rs` always has tests, so that branch is otherwise unreachable
/// and would sit there unexercised.
fn strip_tests(source: &str) -> &str {
    match source.find("\n#[cfg(test)]") {
        Some(at) => &source[..at + 1],
        None => source,
    }
}

/// How the output is laid out across files.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Layout {
    /// Everything in one file. Simple to read and to move around, and what a
    /// small module wants.
    Single,
    /// Functions spread over `part0.rs`, `part1.rs`, … beside a `mod.rs`.
    ///
    /// This is not cosmetic. rustc partitions codegen units along module
    /// boundaries, so a single module of half a million lines becomes one
    /// enormous unit that LLVM works through serially. Splitting it is what
    /// makes a multi-megabyte module compile in a reasonable time — see the
    /// measurement in `README.md`.
    Split {
        /// Roughly how many lines to put in each file.
        ///
        /// Lines rather than functions, because functions are not the same
        /// size. The VoIP module has one function that decompiles to 453
        /// thousand lines and another to 158 thousand; sixteen functions per
        /// file put them in a part of 1.1 million lines, which is the single
        /// enormous compilation unit the split exists to avoid. A function
        /// larger than the budget gets a file to itself — that is as far as
        /// this can go, since a function cannot span modules.
        lines_per_file: usize,
    },
}

impl Layout {
    /// Lines per file when a module is large enough to want splitting.
    ///
    /// Chosen by measurement, not by taste. The 2.0 MiB capture — 3055
    /// functions, 655k lines — compiled by rustc:
    ///
    /// | functions/file | files | time     |
    /// |----------------|-------|----------|
    /// | all            | 1     | 22m49s   |
    /// | 256            | 13    | 7m36s    |
    /// | 64             | 49    | 2m34s    |
    /// | 16             | 192   | 25.7s    |
    /// | 4              | 764   | 10.4s    |
    ///
    /// That run averaged about 3400 lines per file at its sweet spot, which is
    /// where this budget comes from. It is stated in lines because the same
    /// count of functions can be any size at all.
    pub const LINES_PER_FILE: usize = 4000;

    /// Below this, one file. A 478-function capture compiles in about 2.5
    /// seconds whole, and one file is easier to read and to drop into a
    /// project than two hundred.
    pub const SPLIT_ABOVE: usize = 512;

    /// The layout a module of this size wants.
    #[must_use]
    pub fn for_module(module: &Module) -> Self {
        if module.funcs.len() <= Self::SPLIT_ABOVE {
            Self::Single
        } else {
            Self::Split {
                lines_per_file: Self::LINES_PER_FILE,
            }
        }
    }
}

/// One file of generated Rust.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// The file name, relative to wherever the output goes: `mod.rs`, `part0.rs`.
    pub name: String,
    /// Its contents.
    pub contents: String,
}

/// Where an import comes from, for grouping a host skeleton.
///
/// The grouping is the point: 102 methods in one list is a wall, and the same
/// 102 split into "these are WASI", "these are the C++ runtime" and "these
/// forty are yours" is a plan. Only the last group needs anything invented.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum ImportGroup {
    Wasi,
    CxxRuntime,
    EmscriptenRuntime,
    Embind,
    Emval,
    Application,
}

impl ImportGroup {
    fn of(module: &str, field: &str) -> Self {
        if module == "wasi_snapshot_preview1" {
            Self::Wasi
        } else if field.starts_with("_embind_") {
            Self::Embind
        } else if field.starts_with("_emval_") {
            Self::Emval
        } else if field.starts_with("__cxa_")
            || field.starts_with("__syscall")
            || matches!(
                field,
                "abort" | "getentropy" | "__assert_fail" | "__resumeException"
            )
        {
            Self::CxxRuntime
        } else if field.starts_with("emscripten_") || field.starts_with("_emscripten_") {
            Self::EmscriptenRuntime
        } else {
            Self::Application
        }
    }

    fn heading(self) -> &'static str {
        match self {
            Self::Wasi => "WASI. A subset over an in-memory filesystem answers these.",
            Self::CxxRuntime => {
                "The C++ runtime and syscalls. `__cxa_throw` should call `rt::throw`,\n    // which is what the generated `invoke_*` trampolines catch."
            }
            Self::EmscriptenRuntime => "Emscripten's runtime.",
            Self::Embind => {
                "embind: the module registers its classes and functions through\n    // these at startup. What it registers is the high-level API it means to\n    // expose — the one thing in a stripped module that describes itself."
            }
            Self::Emval => "emval: handles to values on the host side.",
            Self::Application => {
                "The application's own callbacks. Nothing but the application can\n    // say what these should do."
            }
        }
    }
}

/// Generates a host skeleton: an `impl Imports` with every method the module
/// still needs, grouped by where it comes from.
///
/// Every body is `todo!()` naming the import. That is deliberate: a skeleton
/// that returned zero would compile, run, and be wrong, and the module could
/// not tell the difference between "not written yet" and "answered 0". A
/// `todo!()` fails loudly at exactly the call that needs writing.
///
/// # Errors
///
/// As [`generate`].
pub fn generate_host(module: &Module) -> Result<String> {
    let analysis = analysis::analyse(module);
    let mut out = String::new();
    out.push_str(concat!(
        "// A host skeleton, generated by unwasm. Edit freely: this is a starting
",
        "// point, not something to regenerate over.
",
        "//
",
        "// Every method is `todo!()` rather than a stub returning zero. A stub that
",
        "// returns zero compiles, runs, and is wrong, and the module cannot tell it
",
        "// apart from an answer.

",
        "use crate::generated::{self, Imports};

",
        "/// State the host needs. Start empty and add as the imports need it.
",
        "#[derive(Debug, Default)]
",
        "pub struct Host {}

",
    ));

    let mut grouped: std::collections::BTreeMap<ImportGroup, Vec<usize>> = Default::default();
    for (index, import) in module.func_imports.iter().enumerate() {
        // The trampolines are generated; they are not the host's to write.
        if analysis
            .invokes
            .iter()
            .any(|invoke| invoke.import == index as u32)
        {
            continue;
        }
        grouped
            .entry(ImportGroup::of(&import.module, &import.field))
            .or_default()
            .push(index);
    }

    let total: usize = grouped.values().map(Vec::len).sum();
    let _ = writeln!(
        out,
        "impl Imports for Host {{\n    // {total} methods. {} of the module's {} imports are Emscripten\n    // exception trampolines and are generated, so they are not here.",
        analysis.invokes.len(),
        module.func_imports.len()
    );

    for (group, indices) in grouped {
        let _ = writeln!(out, "\n    // ---- {}", group.heading());
        for index in indices {
            let import = &module.func_imports[index];
            let ty = module.types.get(import.type_index as usize);
            let signature = ty.map_or_else(String::new, signature_of);
            let result = ty.map_or_else(String::new, return_type);
            let _ = writeln!(
                out,
                "\n    fn {}(&mut self{signature}) {result} {{\n        todo!(\"{}::{}\")\n    }}",
                import_ident(import.module.as_str(), import.field.as_str()),
                import.module,
                import.field
            );
        }
    }
    out.push_str(
        "}
",
    );
    Ok(out)
}

/// Generates a single Rust file from a decoded wasm module.
///
/// # Errors
///
/// Returns [`Error::Unsupported`] for a construct with no faithful Rust form,
/// and [`Error::Invalid`] if the module's own indices do not line up.
pub fn generate(module: &Module) -> Result<String> {
    let mut files = generate_files(module, Layout::Single)?;
    Ok(files.remove(0).contents)
}

/// Generates the output in the requested layout.
///
/// The first file is always `mod.rs`; the rest, if any, are its parts.
///
/// # Errors
///
/// As [`generate`].
pub fn generate_files(module: &Module, layout: Layout) -> Result<Vec<GeneratedFile>> {
    Generator::new(module, layout).run()
}

struct Generator<'a> {
    module: &'a Module,
    layout: Layout,
    analysis: Analysis,
    out: String,
    parts: Vec<GeneratedFile>,
}

impl<'a> Generator<'a> {
    fn new(module: &'a Module, layout: Layout) -> Self {
        Self {
            module,
            layout,
            analysis: analysis::analyse(module),
            out: String::new(),
            parts: Vec::new(),
        }
    }

    fn run(mut self) -> Result<Vec<GeneratedFile>> {
        self.header();
        self.embed_runtime();
        self.data_constants();
        self.imports_trait();
        self.instance_struct();
        self.instance_impl()?;
        let mut files = vec![GeneratedFile {
            name: "mod.rs".to_string(),
            contents: self.out,
        }];
        files.append(&mut self.parts);
        Ok(files)
    }

    fn header(&mut self) {
        self.out.push_str(concat!(
            "// Generated by unwasm. Do not edit: regenerate from the module.\n",
            "//\n",
            "// This is level 0 — a faithful translation. Linear memory is a byte\n",
            "// vector and every wasm value type is its Rust counterpart, so the\n",
            "// arithmetic, the traps and the memory layout are the module's own.\n",
            "// Names come from the module where it kept them and from indices\n",
            "// where it did not.\n",
            "\n",
            "#![allow(\n",
            "    dead_code,\n",
            "    unused_mut,\n",
            "    unused_variables,\n",
            "    unused_assignments,\n",
            "    unused_labels,\n",
            "    unused_parens,\n",
            "    unreachable_code,\n",
            "    non_snake_case,\n",
            "    clippy::all,\n",
            "    clippy::pedantic\n",
            ")]\n\n",
        ));
    }

    fn embed_runtime(&mut self) {
        self.out.push_str("pub mod rt {\n");
        for line in runtime_source().lines() {
            if line.is_empty() {
                self.out.push('\n');
            } else {
                let _ = writeln!(self.out, "    {line}");
            }
        }
        self.out.push_str("}\n\n");
    }

    fn data_constants(&mut self) {
        for (index, segment) in self.module.datas.iter().enumerate() {
            let _ = write!(self.out, "const DATA_{index}: &[u8] = &[");
            for (at, byte) in segment.bytes.iter().enumerate() {
                if at % 16 == 0 {
                    self.out.push_str("\n    ");
                }
                let _ = write!(self.out, "0x{byte:02x}, ");
            }
            self.out.push_str("\n];\n\n");
        }
    }

    /// The host side of the module, as a trait.
    ///
    /// Imports are the one thing a module cannot answer for itself, so they
    /// become required methods rather than stubs returning zero. [`NoImports`]
    /// traps, which keeps "nobody supplied a host" distinguishable from "the
    /// host returned 0" — the distinction the oracle work in wa-wasm-oracle
    /// found the hard way.
    /// Whether an import is one this backend generates rather than asks for.
    fn is_generated(&self, index: usize) -> bool {
        self.analysis
            .invokes
            .iter()
            .any(|invoke| invoke.import == index as u32)
    }

    fn imports_trait(&mut self) {
        self.out
            .push_str("/// What the module needs from its host.\npub trait Imports {\n");
        if !self.analysis.invokes.is_empty() {
            let _ = writeln!(
                self.out,
                "    // {} `invoke_*` imports are not here: they are Emscripten's\n    // exception trampolines, and every part of one is already in this\n    // module — the table, the stack pointer, and its own `setThrew`. They\n    // are generated below rather than asked of you.",
                self.analysis.invokes.len()
            );
        }
        for (index, import) in self.module.func_imports.iter().enumerate() {
            if self.is_generated(index) {
                continue;
            }
            let ty = self.module.types.get(import.type_index as usize);
            let signature = ty.map_or_else(String::new, signature_of);
            let result = ty.map_or_else(String::new, return_type);
            let _ = writeln!(
                self.out,
                "    /// `{}::{}`\n    fn {}(&mut self{signature}) {result};",
                import.module,
                import.field,
                import_ident(import.module.as_str(), import.field.as_str())
            );
        }
        self.out.push_str("}\n\n");

        self.out.push_str(concat!(
            "/// A host that supplies nothing.\n",
            "///\n",
            "/// Every import traps rather than returning a plausible zero: a stub\n",
            "/// that returns zero is a hypothesis, and the module cannot tell it\n",
            "/// apart from an answer.\n",
            "#[derive(Debug, Default, Clone, Copy)]\n",
            "pub struct NoImports;\n\n",
            "impl Imports for NoImports {\n",
        ));
        for (index, import) in self.module.func_imports.iter().enumerate() {
            if self.is_generated(index) {
                continue;
            }
            let ty = self.module.types.get(import.type_index as usize);
            let signature = ty.map_or_else(String::new, signature_of);
            let result = ty.map_or_else(String::new, return_type);
            let _ = writeln!(
                self.out,
                "    fn {}(&mut self{signature}) {result} {{\n        rt::trap(\"unimplemented import: {}::{}\");\n    }}",
                import_ident(import.module.as_str(), import.field.as_str()),
                import.module,
                import.field
            );
        }
        self.out.push_str("}\n\n");
    }

    fn instance_struct(&mut self) {
        self.out.push_str(concat!(
            "/// An instantiated module: its memory, its table and its globals.\n",
            "pub struct Instance<H: Imports = NoImports> {\n",
            "    /// The host.\n    pub host: H,\n",
            "    /// Linear memory.\n    pub memory: rt::Memory,\n",
            "    /// The function table `call_indirect` dispatches through.\n",
            "    /// `u32::MAX` marks an empty slot.\n    pub table: Vec<u32>,\n",
            "    /// Which data segments have been dropped. An active segment is\n",
            "    /// dropped by instantiation itself, as the spec requires.\n",
            "    pub data_dropped: Vec<bool>,\n",
        ));
        for (index, global) in self.module.globals.iter().enumerate() {
            let mutability = if global.mutable {
                "mutable"
            } else {
                "immutable"
            };
            let _ = writeln!(
                self.out,
                "    /// Global #{index} ({mutability}).{}\n    pub {}: {},",
                self.global_note(index as u32),
                global_ident(index as u32, &self.analysis),
                global.ty.rust_name()
            );
        }
        self.out.push_str("}\n\n");
    }

    fn instance_impl(&mut self) -> Result<()> {
        self.out
            .push_str("impl<H: Imports> Instance<H> {\n    /// Instantiates the module: memory, data segments, table, then `start`.\n    pub fn with_host(host: H) -> Self {\n");
        let memory = self
            .module
            .memory
            .clone()
            .unwrap_or(crate::module::MemoryDef {
                min_pages: 0,
                max_pages: None,
                shared: false,
                imported: None,
            });
        let max = match memory.max_pages {
            Some(pages) => format!("Some({pages})"),
            None => "None".to_string(),
        };
        let _ = writeln!(
            self.out,
            "        let mut instance = Self {{\n            host,\n            memory: rt::Memory::new({}, {max}),\n            table: Vec::new(),\n            data_dropped: vec![false; {}],",
            memory.min_pages,
            self.module.datas.len()
        );
        for (index, global) in self.module.globals.iter().enumerate() {
            let _ = writeln!(
                self.out,
                "            {}: {},",
                global_ident(index as u32, &self.analysis),
                const_expr_literal(global.init)
            );
        }
        self.out.push_str("        };\n");

        for (index, segment) in self.module.datas.iter().enumerate() {
            if let Some(offset) = segment.offset {
                let _ = writeln!(
                    self.out,
                    "        instance.memory.init({}, DATA_{index}, 0, DATA_{index}.len() as i32);\n        instance.data_dropped[{index}] = true;",
                    const_expr_literal(offset)
                );
            }
        }

        let table_size = self.table_size();
        if table_size > 0 {
            let _ = writeln!(
                self.out,
                "        instance.table = vec![u32::MAX; {table_size}];"
            );
            for segment in &self.module.elems {
                let Some(ConstExpr::I32(base)) = segment.offset else {
                    continue;
                };
                for (slot, func) in segment.funcs.iter().enumerate() {
                    let _ = writeln!(
                        self.out,
                        "        instance.table[{}] = {func};",
                        base as usize + slot
                    );
                }
            }
        }

        if let Some(start) = self.module.start {
            let _ = writeln!(
                self.out,
                "        instance.{}();",
                function_ident(start, &self.analysis)
            );
        }
        self.out.push_str("        instance\n    }\n\n");

        self.export_wrappers();
        self.import_thunks();
        self.indirect_dispatchers()?;
        // Closes the `impl` block, and emits the functions either inside it or
        // into part files beside it.
        self.functions()?;
        // `new` lives on the concrete instantiation rather than on the generic
        // impl: `Instance::new()` inside `impl<H> Instance<H>` cannot infer `H`
        // at the call site, and every caller would have to spell it out.
        self.out.push_str(concat!(
            "impl Instance<NoImports> {\n",
            "    /// Instantiates with a host that traps on every import.\n",
            "    #[must_use]\n",
            "    pub fn new() -> Self {\n        Self::with_host(NoImports)\n    }\n}\n\n",
            "impl Default for Instance<NoImports> {\n",
            "    fn default() -> Self {\n        Self::new()\n    }\n}\n",
        ));
        Ok(())
    }

    /// Emits the module's functions and closes the `impl` block they live in.
    ///
    /// Under [`Layout::Split`] they go into sibling modules instead, each with
    /// its own `impl` block on the same type — which is legal Rust, and is what
    /// gives rustc the module boundaries it partitions codegen units along.
    fn functions(&mut self) -> Result<()> {
        let import_count = self.module.func_imports.len() as u32;
        let budget = match self.layout {
            Layout::Single => {
                for (at, func) in self.module.funcs.iter().enumerate() {
                    let index = import_count + at as u32;
                    let body = self.function(index, func)?;
                    self.out.push_str(&body);
                }
                self.out.push_str("}\n\n");
                return Ok(());
            }
            // A zero budget would put every function in a file of its own, and
            // that is the most it can mean.
            Layout::Split { lines_per_file } => lines_per_file.max(1),
        };

        self.out.push_str("}\n\n");

        // Fill each part up to the budget. A function larger than the whole
        // budget still goes in one piece — a function cannot span modules — so
        // it lands in a file of its own rather than dragging fifteen others
        // into a million-line compilation unit with it.
        let mut current = String::new();
        let mut lines = 0usize;
        for (at, func) in self.module.funcs.iter().enumerate() {
            let index = import_count + at as u32;
            let body = self.function(index, func)?;
            let body_lines = body.lines().count();
            if lines > 0 && lines + body_lines > budget {
                self.push_part(std::mem::take(&mut current));
                lines = 0;
            }
            current.push_str(&body);
            lines += body_lines;
        }
        if !current.is_empty() {
            self.push_part(current);
        }

        for part in 0..self.parts.len() {
            let _ = writeln!(self.out, "mod part{part};");
        }
        self.out.push('\n');
        Ok(())
    }

    fn push_part(&mut self, functions: String) {
        let mut contents = String::new();
        contents.push_str(PART_HEADER);
        contents.push_str("use super::*;\n\nimpl<H: Imports> Instance<H> {\n");
        contents.push_str(&functions);
        contents.push_str("}\n");
        let name = format!("part{}.rs", self.parts.len());
        self.parts.push(GeneratedFile { name, contents });
    }

    /// The doc comment a global carries when the analysis recognised it.
    ///
    /// The evidence goes in the comment rather than only in the name: "this is
    /// the stack pointer" is a claim, and the reader deserves to see what it
    /// rests on.
    fn global_note(&self, index: u32) -> String {
        match self.analysis.stack_pointer {
            Some(found) if found.global == index => match found.evidence {
                Evidence::Exported => {
                    "\n    ///\n    /// The C stack pointer: the module exports it under that name."
                        .to_string()
                }
                Evidence::Prologue { functions } => format!(
                    "\n    ///\n    /// The C stack pointer, by its use: {functions} functions open by\n    /// subtracting a frame from it and storing it back. The module keeps\n    /// no names, so this is evidence rather than a declaration."
                ),
            },
            _ => String::new(),
        }
    }

    fn table_size(&self) -> usize {
        self.module
            .elems
            .iter()
            .filter_map(|segment| match segment.offset {
                Some(ConstExpr::I32(base)) => Some(base as usize + segment.funcs.len()),
                _ => None,
            })
            .max()
            .unwrap_or(0)
    }

    /// Exports become public methods, so a caller reaches the module by the
    /// name the module publishes rather than by an index.
    fn export_wrappers(&mut self) {
        for (export, name) in exported_functions(self.module) {
            let Some(ty) = self.module.func_type(export.index) else {
                continue;
            };
            let args: Vec<String> = (0..ty.params.len()).map(|at| format!("p{at}")).collect();
            let _ = writeln!(
                self.out,
                "    /// Exported as `{}`.\n    pub fn {name}(&mut self{}) {} {{\n        self.{}({})\n    }}\n",
                escape_doc(&export.name),
                signature_of(ty),
                return_type(ty),
                function_ident(export.index, &self.analysis),
                args.join(", ")
            );
        }
        // A memory or global export tells a reader where the module's own
        // metadata lives, and costs one line to record.
        for export in &self.module.exports {
            match export.kind {
                ExportKind::Global => {
                    let _ = writeln!(
                        self.out,
                        "    /// The module exports global #{} as `{}`.\n    pub fn exported_global_{}(&self) -> {} {{\n        self.{}\n    }}\n",
                        export.index,
                        escape_doc(&export.name),
                        sanitize(&export.name),
                        self.module
                            .globals
                            .get(export.index as usize)
                            .map_or("i32", |global| global.ty.rust_name()),
                        global_ident(export.index, &self.analysis)
                    );
                }
                ExportKind::Memory | ExportKind::Table | ExportKind::Func => {}
            }
        }
    }

    /// Calls to imported functions go through a thunk, so a call site reads the
    /// same whether the callee is defined here or supplied by the host.
    ///
    /// An `invoke_*` import gets a generated trampoline instead — see
    /// [`Self::invoke_trampoline`].
    fn import_thunks(&mut self) {
        for (index, import) in self.module.func_imports.iter().enumerate() {
            let Some(ty) = self.module.types.get(import.type_index as usize) else {
                continue;
            };
            if let Some(invoke) = self
                .analysis
                .invokes
                .iter()
                .find(|invoke| invoke.import == index as u32)
                .copied()
            {
                let ty = ty.clone();
                self.invoke_trampoline(invoke, &ty, import.field.clone());
                continue;
            }
            let args: Vec<String> = (0..ty.params.len()).map(|at| format!("p{at}")).collect();
            let _ = writeln!(
                self.out,
                "    /// Imported from `{}::{}`.\n    pub(crate) fn f{index}(&mut self{}) {} {{\n        self.host.{}({})\n    }}\n",
                import.module,
                import.field,
                signature_of(ty),
                return_type(ty),
                import_ident(import.module.as_str(), import.field.as_str()),
                args.join(", ")
            );
        }
    }

    /// Emits one `invoke_*` trampoline.
    ///
    /// This is Emscripten's glue, in Rust:
    ///
    /// ```js
    /// var sp = stackSave();
    /// try { getWasmTableEntry(index)(a, b); }
    /// catch (e) { stackRestore(sp); if (e !== e+0) throw e; _setThrew(1, 0); }
    /// ```
    ///
    /// The `if (e !== e+0) throw e` is the part worth copying carefully: the
    /// glue re-throws anything that is not one of its own exceptions, so a trap
    /// stays a trap. Catching everything would turn a crash into a quietly
    /// handled error, which is the failure mode a decompiler must not have.
    fn invoke_trampoline(
        &mut self,
        invoke: crate::analysis::Invoke,
        ty: &crate::module::FuncType,
        field: String,
    ) {
        let index = invoke.import;
        let args: Vec<String> = (1..ty.params.len()).map(|at| format!("p{at}")).collect();
        let stack_pointer = global_ident(
            self.analysis
                .stack_pointer
                .expect("a trampoline is only generated with one")
                .global,
            &self.analysis,
        );
        let set_threw_ident = function_ident(
            self.analysis
                .set_threw
                .expect("a trampoline is only generated with one"),
            &self.analysis,
        );
        let zero = ty.results.first().map_or("", |result| result.zero());

        let _ = writeln!(
            self.out,
            "    /// `env::{field}` — generated, not delegated.\n    ///\n    /// Emscripten's exception trampoline: call through the table, and if the\n    /// callee throws, restore the stack pointer and tell the module through\n    /// its own `setThrew`. A trap is not an exception and is re-raised.\n    fn f{index}(&mut self{}) {} {{\n        let saved = self.{stack_pointer};\n        let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {{\n            self.call_indirect_{}(p0{}{})\n        }}));\n        match outcome {{\n            Ok(value) => value,\n            Err(payload) => {{\n                if payload.is::<rt::GuestException>() {{\n                    self.{stack_pointer} = saved;\n                    self.{set_threw_ident}(1, 0);\n                    {zero}\n                }} else {{\n                    std::panic::resume_unwind(payload)\n                }}\n            }}\n        }}\n    }}\n",
            signature_of(ty),
            return_type(ty),
            invoke.callee_type,
            if args.is_empty() { "" } else { ", " },
            args.join(", ")
        );
    }

    /// `call_indirect` becomes a match over the table, one dispatcher per
    /// signature. The type check wasm does at run time is the match arm's
    /// guard: a slot holding a function of another signature falls through to
    /// the trap, exactly as the engine would.
    fn indirect_dispatchers(&mut self) -> Result<()> {
        let mut signatures: BTreeSet<u32> = BTreeSet::new();
        for func in &self.module.funcs {
            for op in &func.body {
                if let Op::CallIndirect { type_index } = op {
                    signatures.insert(*type_index);
                }
            }
        }
        // A trampoline dispatches through the table too, and its signature may
        // appear in no `call_indirect` at all.
        for invoke in &self.analysis.invokes {
            signatures.insert(invoke.callee_type);
        }
        for type_index in signatures {
            let ty = self.module.types.get(type_index as usize).ok_or_else(|| {
                Error::invalid("call_indirect names a missing type", "type section")
            })?;
            let args: Vec<String> = (0..ty.params.len()).map(|at| format!("p{at}")).collect();
            let _ = writeln!(
                self.out,
                "    pub(crate) fn call_indirect_{type_index}(&mut self, index: i32{}) {} {{\n        match self.table.get(index as u32 as usize).copied() {{",
                signature_of(ty),
                return_type(ty)
            );
            let import_count = self.module.func_imports.len() as u32;
            for (at, func) in self.module.funcs.iter().enumerate() {
                if func.type_index != type_index {
                    continue;
                }
                let index = import_count + at as u32;
                let _ = writeln!(
                    self.out,
                    "            Some({index}) => self.{}({}),",
                    function_ident(index, &self.analysis),
                    args.join(", ")
                );
            }
            for (index, import) in self.module.func_imports.iter().enumerate() {
                if import.type_index != type_index {
                    continue;
                }
                let _ = writeln!(
                    self.out,
                    "            Some({index}) => self.f{index}({}),",
                    args.join(", ")
                );
            }
            self.out.push_str(concat!(
                "            Some(u32::MAX) | None => rt::trap(\"uninitialized element\"),\n",
                "            Some(_) => rt::trap(\"indirect call type mismatch\"),\n",
                "        }\n    }\n\n",
            ));
        }
        Ok(())
    }

    /// One function, as text.
    ///
    /// Returned rather than written straight out, because under a split layout
    /// it belongs in a part file rather than in `mod.rs`.
    fn function(&self, index: u32, func: &Func) -> Result<String> {
        let ty = self
            .module
            .types
            .get(func.type_index as usize)
            .ok_or_else(|| {
                Error::invalid(
                    "function refers to a missing type",
                    format!("function #{index}"),
                )
            })?;
        if ty.results.len() > 1 {
            return Err(Error::unsupported(
                "multiple return values",
                format!("function #{index}"),
            ));
        }

        let mut out = String::new();
        if let Some(name) = self.module.func_name(index) {
            let _ = writeln!(out, "    /// `{}`", escape_doc(name));
        } else if let Some(derived) = self.analysis.derived_names.get(&index) {
            // The name is a guess, so the reason travels with it. Without the
            // evidence a reader has to take `parse_xmpp_offer` on trust, and
            // there is nothing else in a stripped module to check it against.
            let _ = writeln!(
                out,
                "    /// Function #{index}. The module names nothing; this one references\n    /// {}, a message no other function\n    /// references — so it is probably `{}`.",
                escape_comment(&derived.evidence),
                escape_doc(&derived.name)
            );
        } else {
            let _ = writeln!(out, "    /// Function #{index}, unnamed in the module.");
        }
        let frame = self.analysis.frames.get(&index);
        if let Some(frame) = frame {
            out.push_str(&frame_summary(frame));
        }
        // `pub(crate)` rather than private: under a split layout the callers
        // live in sibling modules, and a private method would be visible only
        // in the one it was defined in.
        let _ = writeln!(
            out,
            "    pub(crate) fn {}(&mut self{}) {} {{",
            function_ident(index, &self.analysis),
            signature_of(ty),
            return_type(ty)
        );

        out.push_str(&Body::new(self.module, &self.analysis, func, ty, index).emit()?);
        out.push_str("    }\n\n");
        Ok(out)
    }
}

/// A value sitting on the operand stack, and how it may be used.
#[derive(Debug, Clone)]
struct Value {
    code: String,
    ty: ValType,
    /// A read of something that can change — a local, a global, a `let` binding
    /// that is still valid. Folded values are inlined into their consumer, but
    /// must be spilled before anything runs that could change what they read.
    folded: bool,
}

impl Value {
    /// The code, parenthesised unless it plainly does not need to be.
    ///
    /// Folding puts expressions inside other expressions, and Rust's
    /// precedence is not wasm's: `a + b` folded into `{0} as u32` gives
    /// `a + b as u32`, which casts `b` and adds it to `a`. The template cannot
    /// know whether its operand is compound, so the operand answers for
    /// itself — and answers conservatively, since a redundant pair of brackets
    /// costs nothing and a missing pair is a wrong number.
    fn as_operand(&self) -> String {
        if is_atomic(&self.code) {
            self.code.clone()
        } else {
            format!("({})", self.code)
        }
    }
}

/// Whether an expression can sit inside another without brackets.
///
/// The question is only about precedence, so it is answered by looking for an
/// operator *outside* any brackets: `l0.wrapping_sub(2i32)` has none and binds
/// tighter than anything it could be folded into, while `l1 as u32` has one and
/// would bind the wrong way inside `{0} as i64`.
///
/// Anything not understood is treated as compound. A redundant pair of brackets
/// costs a little noise; a missing pair costs a wrong number.
fn is_atomic(code: &str) -> bool {
    let bytes = code.as_bytes();
    let mut depth = 0usize;
    let mut at = 0usize;
    while at < bytes.len() {
        match bytes[at] {
            b'(' | b'[' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            // An operator at the top level means the expression is compound.
            b'+' | b'-' | b'*' | b'/' | b'%' | b'&' | b'|' | b'^' | b'<' | b'>' | b'=' | b'!'
            | b'?' | b',' | b'{' | b'}'
                if depth == 0 =>
            {
                return false;
            }
            // `as`, which is why a cast needs brackets inside another cast.
            b'a' if depth == 0 && code[at..].starts_with("as ") => return false,
            b' ' if depth == 0 => return false,
            _ => {}
        }
        at += 1;
    }
    true
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FrameKind {
    Block,
    Loop,
    If,
}

#[derive(Debug)]
struct Frame {
    kind: FrameKind,
    label: usize,
    result: Option<ValType>,
    /// Height the value stack returns to when the frame closes.
    stack_height: usize,
    /// Set once the frame's code becomes unreachable, so the rest of it is
    /// dropped rather than emitted — wasm's stack is polymorphic after a
    /// branch, and Rust's type checker is not.
    unreachable: bool,
    /// An `if` that has seen its `else`.
    in_else: bool,
}

struct Body<'a> {
    module: &'a Module,
    analysis: &'a Analysis,
    /// This function's C stack frame, when it has one.
    frame: Option<&'a StackFrame>,
    func: &'a Func,
    ty: &'a crate::module::FuncType,
    index: u32,
    out: String,
    stack: Vec<Value>,
    frames: Vec<Frame>,
    temps: usize,
    labels: usize,
    depth: usize,
    unreachable: bool,
    /// Nesting still to be skipped while unreachable.
    skipping: usize,
    /// The instruction after the one being emitted, for the one lookahead this
    /// backend does.
    next_op: Option<Op>,
}

impl<'a> Body<'a> {
    fn new(
        module: &'a Module,
        analysis: &'a Analysis,
        func: &'a Func,
        ty: &'a crate::module::FuncType,
        index: u32,
    ) -> Self {
        Self {
            module,
            analysis,
            frame: analysis.frames.get(&index),
            func,
            ty,
            index,
            out: String::new(),
            stack: Vec::new(),
            frames: Vec::new(),
            temps: 0,
            labels: 0,
            depth: 2,
            unreachable: false,
            skipping: 0,
            next_op: None,
        }
    }

    fn location(&self) -> String {
        format!("function #{}", self.index)
    }

    fn emit(mut self) -> Result<String> {
        // Parameters arrive as `p0..`, locals are declared zeroed, and both are
        // rebound as `l0..` so that `local.set` on a parameter is the same
        // statement as `local.set` on a local.
        for (at, param) in self.ty.params.iter().enumerate() {
            self.line(&format!(
                "let mut {}: {} = p{at};",
                self.local_ident(at as u32),
                param.rust_name()
            ));
        }
        for (at, local) in self.func.locals.iter().enumerate() {
            let at = self.ty.params.len() + at;
            self.line(&format!(
                "let mut {}: {} = {};",
                self.local_ident(at as u32),
                local.rust_name(),
                local.zero()
            ));
        }

        let body = self.func.body.clone();
        for (at, op) in body.iter().enumerate() {
            // The next instruction is worth having for one reason: a Rust
            // string is `i32.const ptr; i32.const len`, and the length is what
            // stops the text from running into the next string.
            self.next_op = body.get(at + 1).cloned();
            self.op(op)?;
        }

        // The function's own result. If control cannot reach here the module
        // already ended in a branch or a trap, and Rust still needs an
        // expression of the right type: `rt::trap` returns `!`, so it fits any.
        if self.unreachable {
            self.line("rt::trap(\"unreachable code reached\")");
        } else if self.ty.results.is_empty() {
            // Nothing to return; anything left on the stack is dropped, as the
            // implicit return does.
        } else {
            let value = self.pop()?;
            self.line(&value.code);
        }
        Ok(self.out)
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.depth {
            self.out.push_str("    ");
        }
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn push(&mut self, code: String, ty: ValType, folded: bool) {
        self.stack.push(Value { code, ty, folded });
    }

    /// How long an expression may get before it is given a name instead.
    ///
    /// wasm's stack consumes each value exactly once, so folding an expression
    /// into its consumer never duplicates work — but it does nest, and nesting
    /// without a limit turns a long chain of arithmetic into one unreadable
    /// line. This is where a line stops being easier to read than two.
    const FOLD_LIMIT: usize = 100;

    /// Pushes a computed value, naming it first.
    ///
    /// Anything that can trap or that touches state goes through here: naming
    /// it is what makes it *happen*, at the point the module says it happens.
    fn push_temp(&mut self, code: &str, ty: ValType) {
        let name = format!("t{}", self.temps);
        self.temps += 1;
        self.line(&format!("let {name}: {} = {code};", ty.rust_name()));
        self.push(name, ty, true);
    }

    /// Pushes an expression that can be folded into whatever consumes it.
    ///
    /// Only for expressions that cannot trap and touch nothing: `a + b` used
    /// once reads better inline than as a `let` two lines up, and one function
    /// in the VoIP module spends 171704 of its 453292 lines on bindings of
    /// exactly that kind.
    ///
    /// Purity is the whole condition, and the reason is `drop`. A folded value
    /// that is dropped is never emitted at all — so folding a division would
    /// lose the trap it owes on a zero divisor, and folding an atomic
    /// read-modify-write would lose the write. The differential tests caught
    /// both within a minute of the first attempt, which is what they are for.
    fn push_pure(&mut self, code: &str, ty: ValType) {
        if code.len() <= Self::FOLD_LIMIT {
            self.push(code.to_string(), ty, true);
        } else {
            self.push_temp(code, ty);
        }
    }

    fn pop(&mut self) -> Result<Value> {
        self.stack
            .pop()
            .ok_or_else(|| Error::invalid("operand stack underflow", self.location()))
    }

    fn pop_n(&mut self, count: usize) -> Result<Vec<Value>> {
        let mut values = Vec::with_capacity(count);
        for _ in 0..count {
            values.push(self.pop()?);
        }
        values.reverse();
        Ok(values)
    }

    /// Names everything still on the stack.
    ///
    /// Called before anything that can change what a folded value reads — a
    /// write to a local or global, a store, a call. Without it, a folded
    /// `local.get 0` pushed before `local.set 0` would read the new value, and
    /// the output would be wrong in a way that only shows up on some inputs.
    fn spill_stack(&mut self) {
        for at in 0..self.stack.len() {
            if !self.stack[at].folded {
                continue;
            }
            let value = self.stack[at].clone();
            let name = format!("t{}", self.temps);
            self.temps += 1;
            self.line(&format!(
                "let {name}: {} = {};",
                value.ty.rust_name(),
                value.code
            ));
            self.stack[at] = Value {
                code: name,
                ty: value.ty,
                folded: false,
            };
        }
    }

    /// Names the given operands, for a call whose receiver is `&mut self`.
    ///
    /// `self.f1(self.f2())` does not borrow-check, and neither does a store
    /// whose value comes from a call. Naming the operands first sidesteps the
    /// whole question instead of relying on two-phase borrows to cover it.
    ///
    /// Only operands that mention `self` need it. An expression over locals —
    /// which is most of them — borrows nothing and can stay where it is, and
    /// leaving it there is most of what folding is worth: every argument of
    /// every call and store would otherwise be named.
    fn spill_operands(&mut self, values: &mut [Value]) {
        for value in values.iter_mut() {
            if !value.code.contains("self.") {
                continue;
            }
            if value.code.starts_with('t') && value.code[1..].chars().all(|c| c.is_ascii_digit()) {
                continue;
            }
            let name = format!("t{}", self.temps);
            self.temps += 1;
            self.line(&format!(
                "let {name}: {} = {};",
                value.ty.rust_name(),
                value.code
            ));
            value.code = name;
            value.folded = false;
        }
    }

    fn block_result(&self, ty: BlockType) -> Result<Option<ValType>> {
        Ok(match ty {
            BlockType::Empty => None,
            BlockType::Value(value) => Some(value),
            BlockType::Func(index) => {
                let signature =
                    self.module.types.get(index as usize).ok_or_else(|| {
                        Error::invalid("block names a missing type", self.location())
                    })?;
                if !signature.params.is_empty() {
                    return Err(Error::unsupported(
                        "block with parameters (multi-value)",
                        self.location(),
                    ));
                }
                match signature.results.len() {
                    0 => None,
                    1 => Some(signature.results[0]),
                    _ => {
                        return Err(Error::unsupported(
                            "block with several results (multi-value)",
                            self.location(),
                        ));
                    }
                }
            }
        })
    }

    /// Opens a frame, declaring its result variable first so that every exit
    /// from the block assigns it rather than carrying a value out.
    fn open(&mut self, kind: FrameKind, ty: BlockType, condition: Option<Value>) -> Result<()> {
        let result = self.block_result(ty)?;
        // Everything already on the stack is named *before* the block opens.
        //
        // wasm's operand stack survives a block boundary and Rust's scopes do
        // not: a value spilled inside the block and consumed after it would
        // name a `let` that has gone out of scope. Spilling out here puts those
        // bindings in the enclosing scope, where both uses can see them. This
        // was not theoretical — it was the first thing a real 236 KiB module
        // hit, in three separate functions.
        self.spill_stack();
        let label = self.labels;
        self.labels += 1;
        if let Some(result) = result {
            self.line(&format!(
                "let mut r{label}: {} = {};",
                result.rust_name(),
                result.zero()
            ));
        }
        match kind {
            FrameKind::Block => self.line(&format!("'b{label}: {{")),
            FrameKind::Loop => self.line(&format!("'b{label}: loop {{")),
            FrameKind::If => {
                let condition = condition.expect("an if frame always has a condition");
                self.line(&format!("'b{label}: {{ if {} != 0 {{", condition.code));
            }
        }
        self.frames.push(Frame {
            kind,
            label,
            result,
            stack_height: self.stack.len(),
            unreachable: false,
            in_else: false,
        });
        self.depth += 1;
        Ok(())
    }

    /// Emits the assignment and jump for a branch to `depth`.
    fn branch(&mut self, depth: u32) -> Result<()> {
        let at = self
            .frames
            .len()
            .checked_sub(depth as usize + 1)
            .ok_or_else(|| Error::invalid("branch past the outermost block", self.location()))?;
        let frame_kind = self.frames[at].kind;
        let frame_label = self.frames[at].label;
        let frame_result = self.frames[at].result;

        // A branch to a loop restarts it, and the loop's parameters (none, at
        // this level) are what it would carry. A branch to a block or an `if`
        // leaves it, carrying the block's result.
        let statement = if frame_kind == FrameKind::Loop {
            format!("continue 'b{frame_label};")
        } else {
            if let Some(ty) = frame_result {
                let value = self.stack.last().cloned().ok_or_else(|| {
                    Error::invalid("branch with no result value", self.location())
                })?;
                let _ = ty;
                self.line(&format!("r{frame_label} = {};", value.code));
            }
            format!("break 'b{frame_label};")
        };
        self.line(&statement);
        Ok(())
    }

    fn go_unreachable(&mut self) {
        self.unreachable = true;
        if let Some(frame) = self.frames.last_mut() {
            frame.unreachable = true;
        }
        let height = self.frames.last().map_or(0, |frame| frame.stack_height);
        self.stack.truncate(height);
    }

    #[allow(
        clippy::too_many_lines,
        reason = "one arm per opcode class; splitting it would hide the dispatch"
    )]
    fn op(&mut self, op: &Op) -> Result<()> {
        // While unreachable, instructions still nest, so the skip has to track
        // depth to know which `end` closes the frame it is inside.
        if self.unreachable {
            match op {
                Op::Block(_) | Op::Loop(_) | Op::If(_) => {
                    self.skipping += 1;
                    return Ok(());
                }
                Op::End | Op::Else if self.skipping > 0 => {
                    if matches!(op, Op::End) {
                        self.skipping -= 1;
                    }
                    return Ok(());
                }
                Op::End | Op::Else => {}
                _ => return Ok(()),
            }
        }

        match op {
            Op::Unreachable => {
                self.line("rt::trap(\"unreachable\");");
                self.go_unreachable();
            }
            Op::Nop => {}
            Op::Block(ty) => self.open(FrameKind::Block, *ty, None)?,
            Op::Loop(ty) => self.open(FrameKind::Loop, *ty, None)?,
            Op::If(ty) => {
                let condition = self.pop()?;
                self.open(FrameKind::If, *ty, Some(condition))?;
            }
            Op::Else => self.emit_else()?,
            Op::End => self.emit_end()?,
            Op::Br(depth) => {
                self.branch(*depth)?;
                self.go_unreachable();
            }
            Op::BrIf(depth) => {
                let condition = self.pop()?;
                self.line(&format!("if {} != 0 {{", condition.code));
                self.depth += 1;
                self.branch(*depth)?;
                self.depth -= 1;
                self.line("}");
            }
            Op::BrTable { targets, default } => {
                let index = self.pop()?;
                self.line(&format!("match {} as u32 {{", index.code));
                self.depth += 1;
                for (at, target) in targets.iter().enumerate() {
                    self.line(&format!("{at} => {{"));
                    self.depth += 1;
                    self.branch(*target)?;
                    self.depth -= 1;
                    self.line("}");
                }
                self.line("_ => {");
                self.depth += 1;
                self.branch(*default)?;
                self.depth -= 1;
                self.line("}");
                self.depth -= 1;
                self.line("}");
                self.go_unreachable();
            }
            Op::Return => {
                if self.ty.results.is_empty() {
                    self.line("return;");
                } else {
                    let value = self.pop()?;
                    self.line(&format!("return {};", value.code));
                }
                self.go_unreachable();
            }
            Op::Call(index) => self.emit_call(*index)?,
            Op::CallIndirect { type_index } => self.emit_call_indirect(*type_index)?,
            Op::Drop => {
                self.pop()?;
            }
            Op::Select => {
                let condition = self.pop()?;
                let alternative = self.pop()?;
                let consequent = self.pop()?;
                let ty = consequent.ty;
                self.push_pure(
                    &format!(
                        "if {} != 0 {{ {} }} else {{ {} }}",
                        condition.code, consequent.code, alternative.code
                    ),
                    ty,
                );
            }
            Op::LocalGet(index) => {
                let ty = self.local_type(*index)?;
                self.push(self.local_ident(*index), ty, true);
            }
            Op::LocalSet(index) => {
                let value = self.pop()?;
                self.spill_stack();
                self.line(&format!("{} = {};", self.local_ident(*index), value.code));
            }
            Op::LocalTee(index) => {
                let value = self.pop()?;
                self.spill_stack();
                self.line(&format!("{} = {};", self.local_ident(*index), value.code));
                let ty = self.local_type(*index)?;
                self.push(self.local_ident(*index), ty, true);
            }
            Op::GlobalGet(index) => {
                let ty = self.global_type(*index)?;
                self.push(
                    format!("self.{}", global_ident(*index, self.analysis)),
                    ty,
                    true,
                );
            }
            Op::GlobalSet(index) => {
                let value = self.pop()?;
                self.spill_stack();
                self.line(&format!(
                    "self.{} = {};",
                    global_ident(*index, self.analysis),
                    value.code
                ));
            }
            Op::I32Const(value) => {
                // A constant that addresses a static string is quoted inline.
                // On a minified module these are often the only readable thing
                // left, and they cost nothing to carry: the comment travels
                // with the expression into whatever consumes it.
                let placements = &self.analysis.placements;
                let text = match self.next_op {
                    // `ptr, len`: the pair a `&str` is passed as. Trying the
                    // length first is what keeps Rust's unterminated strings
                    // from running into each other.
                    Some(Op::I32Const(length)) if length > 0 && length <= 512 => {
                        analysis::placed_text(self.module, placements, *value, Some(length as u32))
                            .or_else(|| {
                                analysis::placed_text(self.module, placements, *value, None)
                            })
                    }
                    _ => analysis::placed_text(self.module, placements, *value, None),
                };
                let code = match text {
                    Some(text) => format!("{} /* {} */", format_i32(*value), escape_comment(&text)),
                    None => format_i32(*value),
                };
                self.push(code, ValType::I32, true);
            }
            Op::I64Const(value) => self.push(format_i64(*value), ValType::I64, true),
            Op::F32Const(value) => self.push(format_f32(*value), ValType::F32, true),
            Op::F64Const(value) => self.push(format_f64(*value), ValType::F64, true),
            Op::Load { kind, mem } => {
                let address = self.pop()?;
                let method = load_method(*kind);
                self.push_temp(
                    &format!("self.memory.{method}({}, {})", address.code, mem.offset),
                    kind.result(),
                );
            }
            Op::Store { kind, mem } => {
                let mut values = self.pop_n(2)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                let (method, cast) = store_method(*kind);
                self.line(&format!(
                    "self.memory.{method}({}, {}, {}{cast});",
                    values[0].code, mem.offset, values[1].code
                ));
            }
            Op::MemorySize => self.push_temp("self.memory.size()", ValType::I32),
            Op::MemoryGrow => {
                let mut values = self.pop_n(1)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                self.push_temp(
                    &format!("self.memory.grow({} as u32)", values[0].code),
                    ValType::I32,
                );
            }
            Op::MemoryFill => {
                let mut values = self.pop_n(3)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                self.line(&format!(
                    "self.memory.fill({}, {}, {});",
                    values[0].code, values[1].code, values[2].code
                ));
            }
            Op::MemoryCopy => {
                let mut values = self.pop_n(3)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                self.line(&format!(
                    "self.memory.copy({}, {}, {});",
                    values[0].code, values[1].code, values[2].code
                ));
            }
            Op::MemoryInit(segment) => {
                let mut values = self.pop_n(3)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                // A dropped segment is an empty one, not a missing one: a
                // zero-length `memory.init` from it still succeeds, and any
                // other length is out of bounds. Reading `data_dropped` into a
                // binding first also keeps the borrow off `self.memory`.
                self.line(&format!(
                    "let segment: &[u8] = if self.data_dropped[{segment}] {{ &[] }} else {{ DATA_{segment} }};"
                ));
                self.line(&format!(
                    "self.memory.init({}, segment, {}, {});",
                    values[0].code, values[1].code, values[2].code
                ));
            }
            Op::DataDrop(segment) => {
                // Dropping is observable, which is easy to talk yourself out of:
                // the bytes are a `const` here, so there is nothing to free. But
                // a later `memory.init` from a dropped segment traps in every
                // engine, and a decompilation that kept returning data would
                // disagree on exactly that call.
                self.line(&format!("self.data_dropped[{segment}] = true;"));
            }
            Op::Atomic { op: atomic, mem } => self.emit_atomic(*atomic, mem.offset)?,
            Op::AtomicFence => {
                // A fence orders memory between threads. With one thread there
                // is nothing to order — but it is recorded rather than dropped,
                // because "the module asked for a fence here" is a fact about
                // the module.
                self.line("// atomic.fence: nothing to order on a single thread");
            }
            Op::Num(num) => self.emit_num(*num)?,
        }
        Ok(())
    }

    /// Emits one atomic instruction.
    ///
    /// Under a single thread the arithmetic is the plain arithmetic; what the
    /// runtime adds is the alignment check, which an atomic has and its plain
    /// counterpart does not. The two blocking instructions are the only place
    /// the thread count is observable, and they are handled there.
    fn emit_atomic(&mut self, atomic: crate::module::Atomic, offset: u64) -> Result<()> {
        use crate::module::AtomicKind;

        let width = atomic.width;
        let result = atomic.ty;
        // An i64 operation's values are i64; an i32's are i32 and go through
        // the runtime's i64 interface, which is why each one casts on the way
        // in and on the way out.
        let cast_in = if result == ValType::I32 {
            " as i64"
        } else {
            ""
        };
        let cast_out = if result == ValType::I32 {
            " as i32"
        } else {
            ""
        };

        match atomic.kind {
            AtomicKind::Load => {
                let address = self.pop()?;
                self.push_temp(
                    &format!(
                        "self.memory.atomic_load({}, {offset}, {width}){cast_out}",
                        address.code
                    ),
                    result,
                );
            }
            AtomicKind::Store => {
                let mut values = self.pop_n(2)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                self.line(&format!(
                    "self.memory.atomic_store({}, {offset}, {width}, {}{cast_in});",
                    values[0].code, values[1].code
                ));
            }
            AtomicKind::Rmw(kind) => {
                let mut values = self.pop_n(2)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                self.push_temp(
                    &format!(
                        "self.memory.atomic_rmw({}, {offset}, {width}, rt::Rmw::{}, {}{cast_in}){cast_out}",
                        values[0].code,
                        kind.rt_name(),
                        values[1].code
                    ),
                    result,
                );
            }
            AtomicKind::Cmpxchg => {
                let mut values = self.pop_n(3)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                self.push_temp(
                    &format!(
                        "self.memory.atomic_cmpxchg({}, {offset}, {width}, {}{cast_in}, {}{cast_in}){cast_out}",
                        values[0].code, values[1].code, values[2].code
                    ),
                    result,
                );
            }
            AtomicKind::Notify => {
                let mut values = self.pop_n(2)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                // The count of threads to wake is popped and unused: with one
                // thread the answer is zero however many were asked for.
                self.push_temp(
                    &format!("self.memory.atomic_notify({}, {offset})", values[0].code),
                    ValType::I32,
                );
            }
            AtomicKind::Wait => {
                let mut values = self.pop_n(3)?;
                self.spill_operands(&mut values);
                self.spill_stack();
                self.push_temp(
                    &format!(
                        "self.memory.atomic_wait({}, {offset}, {width}, {}{cast_in}, {})",
                        values[0].code, values[1].code, values[2].code
                    ),
                    ValType::I32,
                );
            }
        }
        Ok(())
    }

    fn emit_num(&mut self, num: NumOp) -> Result<()> {
        let operands = self.pop_n(num.operands().len())?;
        let code = ops::render(
            num.template(),
            &operands.iter().map(Value::as_operand).collect::<Vec<_>>(),
        );
        // Everything that can trap is spelled as a call into the runtime, so
        // the template says whether this is safe to fold.
        if num.template().starts_with("rt::") {
            self.push_temp(&code, num.result());
        } else {
            self.push_pure(&code, num.result());
        }
        Ok(())
    }

    fn emit_call(&mut self, index: u32) -> Result<()> {
        let ty = self
            .module
            .func_type(index)
            .ok_or_else(|| {
                Error::invalid(
                    format!("call to unknown function #{index}"),
                    self.location(),
                )
            })?
            .clone();
        let mut arguments = self.pop_n(ty.params.len())?;
        self.spill_operands(&mut arguments);
        self.spill_stack();
        let call = format!(
            "self.{}({})",
            function_ident(index, self.analysis),
            arguments
                .iter()
                .map(|value| value.code.clone())
                .collect::<Vec<_>>()
                .join(", ")
        );
        match ty.results.first() {
            None => self.line(&format!("{call};")),
            Some(result) => self.push_temp(&call, *result),
        }
        Ok(())
    }

    fn emit_call_indirect(&mut self, type_index: u32) -> Result<()> {
        let ty = self
            .module
            .types
            .get(type_index as usize)
            .ok_or_else(|| Error::invalid("call_indirect names a missing type", self.location()))?
            .clone();
        let index = self.pop()?;
        let mut arguments = self.pop_n(ty.params.len())?;
        let mut index = [index];
        self.spill_operands(&mut index);
        self.spill_operands(&mut arguments);
        self.spill_stack();
        let mut parts = vec![index[0].code.clone()];
        parts.extend(arguments.iter().map(|value| value.code.clone()));
        let call = format!("self.call_indirect_{type_index}({})", parts.join(", "));
        match ty.results.first() {
            None => self.line(&format!("{call};")),
            Some(result) => self.push_temp(&call, *result),
        }
        Ok(())
    }

    fn emit_else(&mut self) -> Result<()> {
        let frame = self
            .frames
            .last()
            .ok_or_else(|| Error::invalid("`else` outside a block", self.location()))?;
        if frame.kind != FrameKind::If {
            return Err(Error::invalid(
                "`else` closing a non-if block",
                self.location(),
            ));
        }
        let label = frame.label;
        let result = frame.result;
        let height = frame.stack_height;

        // The consequent's result, if it produced one and could reach here.
        if !self.unreachable && result.is_some() {
            let value = self.pop()?;
            self.line(&format!("r{label} = {};", value.code));
        }
        self.stack.truncate(height);
        self.depth -= 1;
        self.line("} else {");
        self.depth += 1;
        self.unreachable = false;
        self.skipping = 0;
        if let Some(frame) = self.frames.last_mut() {
            frame.in_else = true;
            frame.unreachable = false;
        }
        Ok(())
    }

    fn emit_end(&mut self) -> Result<()> {
        let frame = self
            .frames
            .pop()
            .ok_or_else(|| Error::invalid("`end` with no open block", self.location()))?;

        if !self.unreachable && frame.result.is_some() {
            let value = self.pop()?;
            self.line(&format!("r{} = {};", frame.label, value.code));
        }
        self.stack.truncate(frame.stack_height);
        self.depth -= 1;

        match frame.kind {
            FrameKind::Block => self.line("}"),
            // A wasm loop falls out of the bottom; a Rust one repeats, so the
            // fallthrough is spelled out.
            FrameKind::Loop => {
                self.depth += 1;
                self.line("break;");
                self.depth -= 1;
                self.line("}");
            }
            FrameKind::If => self.line("} }"),
        }

        // Control reaches past the frame if the frame could be left by a branch,
        // even when its body ended unreachable. An `if` without an `else` can
        // always fall through the missing branch.
        self.unreachable = false;
        self.skipping = 0;
        if let Some(result) = frame.result {
            self.push(format!("r{}", frame.label), result, false);
        }
        Ok(())
    }

    /// The Rust name for a wasm local.
    ///
    /// The one local worth a real name is the frame base: `frame` says what it
    /// is, where `l3` says only where it was. Everything else keeps its index,
    /// because the index is what a `local.get 3` in the bytes refers to and a
    /// reader tracing one should not have to translate.
    fn local_ident(&self, index: u32) -> String {
        match self.frame {
            Some(frame) if frame.base_local == index => "frame".to_string(),
            _ => format!("l{index}"),
        }
    }

    fn local_type(&self, index: u32) -> Result<ValType> {
        let at = index as usize;
        if let Some(param) = self.ty.params.get(at) {
            return Ok(*param);
        }
        self.func
            .locals
            .get(at - self.ty.params.len())
            .copied()
            .ok_or_else(|| {
                Error::invalid(format!("local #{index} does not exist"), self.location())
            })
    }

    fn global_type(&self, index: u32) -> Result<ValType> {
        self.module
            .globals
            .get(index as usize)
            .map(|global| global.ty)
            .ok_or_else(|| {
                Error::invalid(format!("global #{index} does not exist"), self.location())
            })
    }
}

fn load_method(kind: LoadKind) -> &'static str {
    match kind {
        LoadKind::I32 => "load32",
        LoadKind::I64 => "load64",
        LoadKind::F32 => "load_f32",
        LoadKind::F64 => "load_f64",
        LoadKind::I32Load8S => "load8_s",
        LoadKind::I32Load8U => "load8_u",
        LoadKind::I32Load16S => "load16_s",
        LoadKind::I32Load16U => "load16_u",
        // The i64 narrow loads read the same bytes and widen to i64, which the
        // `as i64` in `load_cast` supplies.
        LoadKind::I64Load8S => "load8_s_i64",
        LoadKind::I64Load8U => "load8_u_i64",
        LoadKind::I64Load16S => "load16_s_i64",
        LoadKind::I64Load16U => "load16_u_i64",
        LoadKind::I64Load32S => "load32_s_i64",
        LoadKind::I64Load32U => "load32_u_i64",
    }
}

/// The runtime method for a store, and the cast its value needs.
///
/// The integer stores all take an `i64` and truncate, so an `i32` value widens
/// and an `i64` one does not. Widening an `i64` would compile and read as if
/// something were being converted.
fn store_method(kind: StoreKind) -> (&'static str, &'static str) {
    match kind {
        StoreKind::I32 => ("store32", " as i64"),
        StoreKind::I64 => ("store64", ""),
        StoreKind::F32 => ("store_f32", ""),
        StoreKind::F64 => ("store_f64", ""),
        StoreKind::I32Store8 => ("store8", " as i64"),
        StoreKind::I32Store16 => ("store16", " as i64"),
        StoreKind::I64Store8 => ("store8", ""),
        StoreKind::I64Store16 => ("store16", ""),
        StoreKind::I64Store32 => ("store32", ""),
    }
}

/// The Rust name of a function.
///
/// The index always leads: `f4213`, and `f4213_parse_xmpp_offer` when a name
/// could be guessed from the module's own log messages. Keeping the index is
/// what makes the guess safe to make — a reader tracing `call 4213` in the
/// bytes finds it either way, and a wrong guess costs a misleading suffix
/// rather than a lost thread.
#[must_use]
pub fn function_ident(index: u32, analysis: &Analysis) -> String {
    match analysis.derived_names.get(&index) {
        Some(derived) => format!("f{index}_{}", sanitize(&derived.name)),
        None => format!("f{index}"),
    }
}

/// The method name each exported function gets, in module order.
///
/// Public because anything that calls into generated code — a test harness, a
/// driver, a person — needs the same answer the backend used. Deriving it twice
/// is how a harness ends up calling a method that was never emitted.
#[must_use]
pub fn exported_functions(module: &Module) -> Vec<(&crate::module::Export, String)> {
    let mut used: BTreeSet<String> = BTreeSet::new();
    let mut out = Vec::new();
    for export in &module.exports {
        if export.kind != ExportKind::Func {
            continue;
        }
        let mut name = sanitize(&export.name);
        // Two exports can sanitise onto the same identifier — `loop` becomes
        // `loop_`, and so does `loop_`. The later one moves.
        while !used.insert(name.clone()) {
            name = format!("{name}_{}", export.index);
        }
        out.push((export, name));
    }
    out
}

/// The doc comment describing a function's stack frame.
///
/// The frame is the part of a C function that wasm cannot show directly: its
/// locals live in linear memory, addressed off a base the prologue reserves.
/// Naming the slots does not recover the variables, but it does say how many
/// there are, how wide, and which are read before they are written.
fn frame_summary(frame: &StackFrame) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "    ///");
    let _ = writeln!(
        out,
        "    /// Stack frame: {} bytes, based at `frame`{}.",
        frame.size,
        if frame.publishes {
            ", published to the stack pointer"
        } else {
            // Worth saying: it is how a leaf function is spelled.
            ", not published (nothing is called while it is live)"
        }
    );
    if frame.escapes {
        // Saying this plainly matters: the slots below are what could be
        // followed, not what is there.
        let _ = writeln!(
            out,
            "    /// The address leaves this function, so the slots below are only\n    /// the accesses this analysis could follow — not the whole frame."
        );
    }
    if frame.slots.is_empty() {
        let _ = writeln!(out, "    /// No slot accesses were resolved.");
        return out;
    }
    let _ = writeln!(out, "    ///");
    let _ = writeln!(out, "    /// | offset | width | reads | writes |");
    let _ = writeln!(out, "    /// |--------|-------|-------|--------|");
    for (offset, slot) in &frame.slots {
        let _ = writeln!(
            out,
            "    /// | +{offset} | {}B | {} | {} |",
            slot.width, slot.reads, slot.writes
        );
    }
    out
}

/// The field name a global gets.
///
/// Indices stay in the name — `g0_stack_pointer`, not `stack_pointer` — because
/// the index is what every other view of the module uses, and a reader tracing
/// a `global.get 0` should not have to work out which field that became.
fn global_ident(index: u32, analysis: &Analysis) -> String {
    match analysis.stack_pointer {
        Some(found) if found.global == index => format!("g{index}_stack_pointer"),
        _ => format!("g{index}"),
    }
}

/// Makes text safe to sit inside a `/* */` comment.
///
/// A string containing `*/` would otherwise close the comment early and the
/// output would not compile — which, for this project, is the one unacceptable
/// outcome. Newlines and tabs are escaped for the same reason a one-line
/// comment wants to stay on one line.
fn escape_comment(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for ch in text.chars() {
        match ch {
            '*' => out.push('∗'),
            '/' => out.push('∕'),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '"' => out.push('\''),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

fn signature_of(ty: &crate::module::FuncType) -> String {
    let mut signature = String::new();
    for (at, param) in ty.params.iter().enumerate() {
        let _ = write!(signature, ", p{at}: {}", param.rust_name());
    }
    signature
}

fn return_type(ty: &crate::module::FuncType) -> String {
    match ty.results.first() {
        None => String::new(),
        Some(result) => format!("-> {}", result.rust_name()),
    }
}

fn const_expr_literal(expr: ConstExpr) -> String {
    match expr {
        ConstExpr::I32(value) => format_i32(value),
        ConstExpr::I64(value) => format_i64(value),
        ConstExpr::F32(value) => format_f32(value),
        ConstExpr::F64(value) => format_f64(value),
        // An initialiser reading another global can only read an imported one,
        // which this level refuses at parse time; nothing else can reach here.
        ConstExpr::GlobalGet(index) => format!("/* global.get {index} */ 0"),
    }
}

/// `i32::MIN` has no negative literal in Rust: `-2147483648` is parsed as a
/// negation of a literal that does not fit.
fn format_i32(value: i32) -> String {
    if value == i32::MIN {
        "i32::MIN".to_string()
    } else {
        format!("{value}i32")
    }
}

fn format_i64(value: i64) -> String {
    if value == i64::MIN {
        "i64::MIN".to_string()
    } else {
        format!("{value}i64")
    }
}

/// Floats are written by their bits. A decimal literal would be a rounding of
/// the module's constant, and NaN and the infinities have no literal at all.
fn format_f32(value: f32) -> String {
    format!("f32::from_bits(0x{:08x}u32)", value.to_bits())
}

fn format_f64(value: f64) -> String {
    format!("f64::from_bits(0x{:016x}u64)", value.to_bits())
}

/// Turns an exported name into a Rust identifier.
///
/// Minified modules export names like `a`, `$`, and single non-ASCII
/// characters. The mapping only has to be legal and stable; the original is
/// recorded in the doc comment above the wrapper.
fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (at, ch) in name.chars().enumerate() {
        let usable = ch.is_ascii_alphanumeric() || ch == '_';
        if usable && !(at == 0 && ch.is_ascii_digit()) {
            out.push(ch);
        } else if usable {
            out.push('_');
            out.push(ch);
        } else {
            let _ = write!(out, "_{:x}", ch as u32);
        }
    }
    if out.is_empty() {
        out.push_str("_empty");
    }
    if is_rust_keyword(&out) {
        out.push('_');
    }
    out
}

/// The trait method an import becomes. Both halves are sanitised, so
/// `wasi_snapshot_preview1::fd_write` and a minified `a::b` both land on
/// something legal and readable.
fn import_ident(module: &str, field: &str) -> String {
    format!("{}_{}", sanitize(module), sanitize(field))
}

fn is_rust_keyword(name: &str) -> bool {
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false",
        "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
        "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
        "unsafe", "use", "where", "while", "async", "await", "box", "final", "macro", "override",
        "priv", "try", "typeof", "unsized", "virtual", "yield", "abstract", "become", "do",
    ];
    KEYWORDS.contains(&name)
}

/// Keeps a module's own text from closing the doc comment it is quoted in.
fn escape_doc(text: &str) -> String {
    text.replace('\\', "\\\\").replace('`', "'")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stripping_tests_leaves_a_file_that_has_none_alone() {
        assert_eq!(strip_tests("fn f() {}\n"), "fn f() {}\n");
        assert_eq!(
            strip_tests("fn f() {}\n#[cfg(test)]\nmod tests {}\n"),
            "fn f() {}\n"
        );
    }

    #[test]
    fn identifiers_stay_legal_whatever_the_module_calls_things() {
        assert_eq!(sanitize("add"), "add");
        assert_eq!(sanitize("a"), "a");
        // A digit cannot start an identifier, and a symbol cannot appear in one.
        assert_eq!(sanitize("0start"), "_0start");
        assert_eq!(sanitize("$"), "_24");
        assert_eq!(sanitize("with space"), "with_20space");
        assert_eq!(sanitize("café"), "caf_e9");
        assert_eq!(sanitize(""), "_empty");
        // Keywords get out of their own way.
        assert_eq!(sanitize("loop"), "loop_");
        assert_eq!(sanitize("self"), "self_");
        assert_eq!(sanitize("Self"), "Self_");
        assert!(is_rust_keyword("match"));
        assert!(!is_rust_keyword("matches"));
    }

    #[test]
    fn an_import_with_no_usable_name_falls_back_to_its_index() {
        assert_eq!(import_ident("env", "add"), "env_add");
        assert_eq!(
            import_ident("wasi_snapshot_preview1", "fd_write"),
            "wasi_snapshot_preview1_fd_write"
        );
    }

    #[test]
    fn the_extreme_integers_are_written_as_constants_not_negations() {
        // `-2147483648i32` does not parse: it is a negation of a literal that
        // does not fit.
        assert_eq!(format_i32(i32::MIN), "i32::MIN");
        assert_eq!(format_i64(i64::MIN), "i64::MIN");
        assert_eq!(format_i32(-1), "-1i32");
        assert_eq!(format_i64(0), "0i64");
    }

    #[test]
    fn floats_are_written_by_their_bits() {
        assert_eq!(format_f32(1.0), "f32::from_bits(0x3f800000u32)");
        assert_eq!(format_f64(0.0), "f64::from_bits(0x0000000000000000u64)");
        // The cases with no literal form at all.
        assert_eq!(format_f32(f32::NAN), "f32::from_bits(0x7fc00000u32)");
        assert_eq!(
            format_f64(f64::INFINITY),
            "f64::from_bits(0x7ff0000000000000u64)"
        );
    }

    #[test]
    fn every_constant_initialiser_has_a_literal() {
        assert_eq!(const_expr_literal(ConstExpr::I32(1)), "1i32");
        assert_eq!(const_expr_literal(ConstExpr::I64(-1)), "-1i64");
        assert!(const_expr_literal(ConstExpr::F32(1.0)).starts_with("f32::from_bits"));
        assert!(const_expr_literal(ConstExpr::F64(1.0)).starts_with("f64::from_bits"));
        // Reading another global can only mean an imported one, which the
        // frontend refuses; the comment records what was there.
        assert_eq!(
            const_expr_literal(ConstExpr::GlobalGet(3)),
            "/* global.get 3 */ 0"
        );
    }

    #[test]
    fn quoted_text_stays_on_one_line_and_inside_its_comment() {
        // A string containing the comment terminator would close it early and
        // the output would not compile — the one thing that must never happen.
        assert!(!escape_comment("end */ here").contains("*/"));
        // Newlines and tabs would break the line the comment sits on.
        assert_eq!(escape_comment("a\nb"), "\"a\\nb\"");
        assert_eq!(escape_comment("a\tb"), "\"a\\tb\"");
        assert_eq!(escape_comment("say \"this\""), "\"say 'this'\"");
        assert_eq!(escape_comment("plain"), "\"plain\"");
    }

    #[test]
    fn brackets_go_where_precedence_needs_them_and_nowhere_else() {
        // A name, a call, and something already bracketed need none.
        for atomic in [
            "l0",
            "t7",
            "frame",
            "self.g0_stack_pointer",
            "5i32",
            "l0.wrapping_sub(2i32)",
            "self.memory.load32(l0, 4)",
            "(a + b)",
            "f32::from_bits(0x3f800000u32)",
        ] {
            assert!(is_atomic(atomic), "{atomic} was bracketed needlessly");
        }
        // Anything with an operator outside brackets does.
        for compound in [
            "l0 as u32",
            "a + b",
            "(a) + (b)",
            "l0 >> 2",
            "x as u32 as i64",
            "if c != 0 { a } else { b }",
        ] {
            assert!(!is_atomic(compound), "{compound} needs brackets");
        }
    }

    #[test]
    fn an_operand_brackets_itself_when_it_has_to() {
        let name = Value {
            code: "l3".to_string(),
            ty: ValType::I32,
            folded: true,
        };
        assert_eq!(name.as_operand(), "l3");
        let compound = Value {
            code: "l3 as u32".to_string(),
            ty: ValType::I32,
            folded: true,
        };
        assert_eq!(compound.as_operand(), "(l3 as u32)");
    }

    #[test]
    fn a_frame_with_no_resolved_slots_says_so() {
        // A frame whose address escapes immediately: it has a size, and nothing
        // else could be worked out. Printing an empty table would read as "no
        // slots", which is a different claim.
        let summary = frame_summary(&StackFrame {
            size: 16,
            base_local: 0,
            slots: std::collections::BTreeMap::new(),
            escapes: true,
            publishes: true,
        });
        assert!(
            summary.contains("No slot accesses were resolved"),
            "{summary}"
        );
        assert!(!summary.contains("| offset |"));
    }

    #[test]
    fn a_stack_pointer_found_by_its_use_says_how_many_prologues() {
        let module = Module {
            globals: vec![crate::module::GlobalDef {
                ty: ValType::I32,
                mutable: true,
                init: ConstExpr::I32(0),
            }],
            ..Module::default()
        };
        let mut generator = Generator::new(&module, Layout::Single);
        generator.analysis.stack_pointer = Some(crate::analysis::StackPointer {
            global: 0,
            evidence: Evidence::Prologue { functions: 214 },
        });
        let note = generator.global_note(0);
        assert!(note.contains("214 functions"), "{note}");
        assert!(note.contains("evidence rather than a declaration"));
    }

    #[test]
    fn a_doc_comment_cannot_be_closed_by_the_module_it_quotes() {
        assert_eq!(escape_doc("plain"), "plain");
        assert_eq!(escape_doc("with `ticks`"), "with 'ticks'");
        assert_eq!(escape_doc(r"back\slash"), r"back\\slash");
    }

    #[test]
    fn every_load_and_store_maps_to_a_runtime_method() {
        for kind in [
            LoadKind::I32,
            LoadKind::I64,
            LoadKind::F32,
            LoadKind::F64,
            LoadKind::I32Load8S,
            LoadKind::I32Load8U,
            LoadKind::I32Load16S,
            LoadKind::I32Load16U,
            LoadKind::I64Load8S,
            LoadKind::I64Load8U,
            LoadKind::I64Load16S,
            LoadKind::I64Load16U,
            LoadKind::I64Load32S,
            LoadKind::I64Load32U,
        ] {
            let method = load_method(kind);
            assert!(method.starts_with("load"), "{method}");
            // An i64 load must produce an i64, or the generated `let` will not
            // type-check against the value it binds.
            if kind.result() == ValType::I64 && method != "load64" {
                assert!(
                    method.ends_with("_i64"),
                    "{method} widens to the wrong type"
                );
            }
        }
        for kind in [
            StoreKind::I32,
            StoreKind::I64,
            StoreKind::F32,
            StoreKind::F64,
            StoreKind::I32Store8,
            StoreKind::I32Store16,
            StoreKind::I64Store8,
            StoreKind::I64Store16,
            StoreKind::I64Store32,
        ] {
            let (method, cast) = store_method(kind);
            assert!(method.starts_with("store"), "{method}");
            // The integer stores take an i64 value, so an i32 has to widen.
            let widens = matches!(
                kind,
                StoreKind::I32 | StoreKind::I32Store8 | StoreKind::I32Store16
            );
            assert_eq!(widens, cast == " as i64", "{method} casts wrongly");
        }
    }

    #[test]
    fn a_signature_becomes_parameters_and_a_return_type() {
        let ty = crate::module::FuncType {
            params: vec![ValType::I32, ValType::F64],
            results: vec![ValType::I64],
        };
        assert_eq!(signature_of(&ty), ", p0: i32, p1: f64");
        assert_eq!(return_type(&ty), "-> i64");
        let void = crate::module::FuncType::default();
        assert_eq!(signature_of(&void), "");
        assert_eq!(return_type(&void), "");
    }
}

#[cfg(test)]
mod ir_tests {
    //! Cases built as IR rather than as bytes.
    //!
    //! wasmparser rejects an unbalanced `end` or a stray `else` while decoding,
    //! so no module file can reach the checks below. They are still the right
    //! thing for the backend to do — the alternative is an `expect` that turns a
    //! decoder change into a panic — and building the IR directly is how they
    //! get exercised.

    use super::*;
    use crate::module::{Func, FuncType, GlobalDef, MemoryDef};

    fn module_with(body: Vec<Op>, results: Vec<ValType>, extra_types: Vec<FuncType>) -> Module {
        let mut types = vec![FuncType {
            params: Vec::new(),
            results,
        }];
        types.extend(extra_types);
        Module {
            types,
            funcs: vec![Func {
                type_index: 0,
                locals: Vec::new(),
                body,
            }],
            ..Module::default()
        }
    }

    fn error_for(body: Vec<Op>) -> String {
        let module = module_with(body, Vec::new(), Vec::new());
        generate(&module)
            .expect_err("the body does not add up")
            .to_string()
    }

    #[test]
    fn an_end_with_nothing_open_is_reported() {
        assert!(error_for(vec![Op::End]).contains("`end` with no open block"));
    }

    #[test]
    fn an_else_with_nothing_open_is_reported() {
        assert!(error_for(vec![Op::Else]).contains("`else` outside a block"));
    }

    #[test]
    fn an_else_closing_a_plain_block_is_reported() {
        let message = error_for(vec![Op::Block(BlockType::Empty), Op::Else]);
        assert!(
            message.contains("`else` closing a non-if block"),
            "{message}"
        );
    }

    #[test]
    fn a_block_yielding_several_values_is_refused() {
        let module = module_with(
            vec![Op::Block(BlockType::Func(1)), Op::End],
            Vec::new(),
            vec![FuncType {
                params: Vec::new(),
                results: vec![ValType::I32, ValType::I32],
            }],
        );
        let message = generate(&module).expect_err("multi-value").to_string();
        assert!(message.contains("several results"), "{message}");
    }

    #[test]
    fn a_block_typed_by_a_signature_that_yields_nothing_is_fine() {
        let module = module_with(
            vec![Op::Block(BlockType::Func(1)), Op::End],
            Vec::new(),
            vec![FuncType::default()],
        );
        let code = generate(&module).expect("a void block is a plain block");
        assert!(code.contains("'b0: {"), "{code}");
    }

    #[test]
    fn a_global_initialised_from_another_global_is_carried_through() {
        // Only an imported global can mean this, and those are refused at parse
        // time — so this shape only arrives when the IR is built by hand.
        let module = Module {
            globals: vec![GlobalDef {
                ty: ValType::I32,
                mutable: false,
                init: ConstExpr::GlobalGet(0),
            }],
            memory: Some(MemoryDef {
                min_pages: 1,
                max_pages: None,
                shared: false,
                imported: None,
            }),
            ..Module::default()
        };
        let code = generate(&module).expect("it generates");
        assert!(code.contains("/* global.get 0 */ 0"), "{code}");
    }

    #[test]
    fn an_export_naming_a_missing_function_is_left_out() {
        let module = Module {
            exports: vec![crate::module::Export {
                name: "ghost".into(),
                kind: ExportKind::Func,
                index: 9,
            }],
            ..Module::default()
        };
        let code = generate(&module).expect("it generates");
        assert!(!code.contains("pub fn ghost"), "{code}");
    }

    #[test]
    fn an_exported_global_that_is_not_there_falls_back_to_i32() {
        let module = Module {
            exports: vec![crate::module::Export {
                name: "missing".into(),
                kind: ExportKind::Global,
                index: 4,
            }],
            ..Module::default()
        };
        let code = generate(&module).expect("it generates");
        assert!(
            code.contains("exported_global_missing(&self) -> i32"),
            "{code}"
        );
    }

    #[test]
    fn an_import_whose_type_is_missing_still_produces_a_trait_method() {
        // A module can name a type index that is not there. The trait method
        // has to exist regardless, or the generated code will not compile.
        let module = Module {
            func_imports: vec![crate::module::ImportedFunc {
                module: "env".into(),
                field: "mystery".into(),
                type_index: 7,
            }],
            ..Module::default()
        };
        let code = generate(&module).expect("it generates");
        assert!(code.contains("fn env_mystery(&mut self)"), "{code}");
    }
}
